import os
import configparser

from datetime import datetime
from flask import Flask, request, jsonify
from flask_cors import CORS
from hana_ml import dataframe

import math
import pandas as pd
import numpy as np
import re

def nan_to_null(df):
    """Convert all NaN or NaT in a DataFrame to None for JSON serialization."""
    return df.replace({np.nan: None, pd.NaT: None})

# Check if the application is running on Cloud Foundry
if 'VCAP_APPLICATION' in os.environ:
    from app.utilities_hana import kmeans_and_tsne  # works in CF
    
    # Running on Cloud Foundry, use environment variables
    hanaURL = os.getenv('DB_ADDRESS')
    hanaPort = os.getenv('DB_PORT')
    hanaUser = os.getenv('DB_USER')
    hanaPW = os.getenv('DB_PASSWORD')
else:
    from utilities_hana import kmeans_and_tsne  # works in local machine
    
    # Not running on Cloud Foundry, read from config.ini file
    config = configparser.ConfigParser()
    config.read('config.ini')
    hanaURL = config['database']['address']
    hanaPort = config['database']['port']
    hanaUser = config['database']['user']
    hanaPW = config['database']['password']

# Step 1: Establish a connection to SAP HANA
connection = dataframe.ConnectionContext(hanaURL, hanaPort, hanaUser, hanaPW)

app = Flask(__name__)
#CORS(app, origins=["http://localhost:30000"], 
#     methods=["GET", "POST", "OPTIONS"],
#     allow_headers=["Content-Type"])

CORS(app)

# -------------------------------
# Table creation utilities
# -------------------------------
def create_categories_table_if_not_exists():
    create_table_sql = """
        DO BEGIN
            DECLARE table_exists INT;
            
            -- Check and create CATEGORIES table
            SELECT COUNT(*) INTO table_exists
            FROM SYS.TABLES 
            WHERE TABLE_NAME = 'CATEGORIES' AND SCHEMA_NAME = CURRENT_SCHEMA;
            
            IF table_exists = 0 THEN
                CREATE TABLE CATEGORIES (
                    "index" INTEGER,
                    "category_label" NVARCHAR(100),
                    "category_descr" NVARCHAR(5000),
                    "category_embedding" REAL_VECTOR 
                        GENERATED ALWAYS AS VECTOR_EMBEDDING("category_descr", 'DOCUMENT', 'SAP_NEB.20240715')
                );
            END IF;
        END
    """
    cursor = connection.connection.cursor()
    cursor.execute(create_table_sql)
    cursor.close()

def create_project_by_category_table_if_not_exists():
    create_table_sql = """
        DO BEGIN
            DECLARE table_exists INT;
            
            SELECT COUNT(*) INTO table_exists
            FROM SYS.TABLES 
            WHERE TABLE_NAME = 'PROJECT_BY_CATEGORY' AND SCHEMA_NAME = CURRENT_SCHEMA;
            
            IF table_exists = 0 THEN
                CREATE TABLE PROJECT_BY_CATEGORY (
                    PROJECT_ID NVARCHAR(255),
                    CATEGORY_ID INT
                );
            END IF;
        END
    """
    cursor = connection.connection.cursor()
    cursor.execute(create_table_sql)
    cursor.close()  

def create_clustering_table_if_not_exists():
    create_table_sql = """
        DO BEGIN
            DECLARE table_exists INT;
            
            -- CLUSTERING table
            SELECT COUNT(*) INTO table_exists
            FROM SYS.TABLES 
            WHERE TABLE_NAME = 'CLUSTERING' AND SCHEMA_NAME = CURRENT_SCHEMA;
            
            IF table_exists = 0 THEN
                CREATE TABLE CLUSTERING (
                    PROJECT_NUMBER NVARCHAR(255),
                    x DOUBLE,
                    y DOUBLE,
                    CLUSTER_ID INT
                );
            END IF;
            
            -- CLUSTERING_DATA table
            SELECT COUNT(*) INTO table_exists
            FROM SYS.TABLES 
            WHERE TABLE_NAME = 'CLUSTERING_DATA' AND SCHEMA_NAME = CURRENT_SCHEMA;
            
            IF table_exists = 0 THEN
                CREATE TABLE CLUSTERING_DATA (
                    CLUSTER_ID INT,
                    CLUSTER_DESCRIPTION NVARCHAR(255),
                    EMBEDDING REAL_VECTOR GENERATED ALWAYS AS VECTOR_EMBEDDING(CLUSTER_DESCRIPTION, 'DOCUMENT', 'SAP_NEB.20240715')
                );
            END IF;
        END
    """
    cursor = connection.connection.cursor()
    cursor.execute(create_table_sql)
    cursor.close()  

def create_table_if_not_exists(schema_name, table_name):
    create_table_sql = f"""
        DO BEGIN
            DECLARE table_exists INT;
            SELECT COUNT(*) INTO table_exists
            FROM SYS.TABLES 
            WHERE TABLE_NAME = '{table_name.upper()}' AND SCHEMA_NAME = '{schema_name.upper()}';
            
            IF table_exists = 0 THEN
                CREATE TABLE {schema_name}.{table_name} (
                    TEXT_ID INT GENERATED BY DEFAULT AS IDENTITY,
                    TEXT NVARCHAR(5000),
                    EMBEDDING REAL_VECTOR GENERATED ALWAYS AS VECTOR_EMBEDDING(TEXT, 'DOCUMENT', 'SAP_NEB.20240715')
                );
            END IF;
        END
    """
    cursor = connection.connection.cursor()
    cursor.execute(create_table_sql)
    cursor.close()  

# -------------------------------
# Flask Endpoints
# -------------------------------
@app.route('/update_categories_and_projects', methods=['POST'])
def update_categories_and_projects():
    data = request.get_json()
    categories = data
    
    if not categories:
        return jsonify({"error": "No categories provided"}), 400
    
    cursor = connection.connection.cursor()
    
    # Ensure tables exist
    create_categories_table_if_not_exists()
    cursor.execute("TRUNCATE TABLE CATEGORIES")
    
    create_project_by_category_table_if_not_exists()
    cursor.execute("TRUNCATE TABLE PROJECT_BY_CATEGORY")
    
    # Insert categories
    for index, (title, description) in enumerate(categories.items()):
        insert_sql = f"""
            INSERT INTO CATEGORIES ("index", "category_label", "category_descr")
            VALUES ({index}, '{title.replace("'", "''")}', '{description.replace("'", "''")}')
        """
        cursor.execute(insert_sql)
    
    categories_df = dataframe.DataFrame(connection, 'SELECT * FROM CATEGORIES')
    
    # Fetch bookings to match against categories
    bookings_df = dataframe.DataFrame(connection, 'SELECT "NSMAN_ID", "STATUS_CODE", "TOPIC" FROM MHA_ADVISORIES4')
    
    # Match bookings to categories using COSINE similarity on TOPIC or STATUS_CODE mapping
    for booking in bookings_df.collect().to_dict(orient='records'):
        nsman_id = booking['NSMAN_ID']
        topic = booking.get('TOPIC', '')  # Optional field
        status_code = booking.get('STATUS_CODE', '')  # Optional mapping
        
        if not nsman_id:
            continue
        
        similarities = []
        for category in categories_df.collect().to_dict(orient='records'):
            category_id = category['index']
            category_description = category['category_descr']
            
            # Compute similarity only if topic exists
            if topic:
                similarity_sql = f"""
                    SELECT COSINE_SIMILARITY(
                        VECTOR_EMBEDDING('{topic.replace("'", "''")}', 'DOCUMENT', 'SAP_NEB.20240715'),
                        VECTOR_EMBEDDING('{category_description.replace("'", "''")}', 'DOCUMENT', 'SAP_NEB.20240715')
                    ) AS similarity
                    FROM DUMMY
                """
                similarity_df = dataframe.DataFrame(connection, similarity_sql)
                similarity_results = similarity_df.collect()
                if not similarity_results.empty:
                    similarity = similarity_results.iloc[0]['SIMILARITY']
                    similarities.append((category_id, similarity))
        
        # If similarity search found a match, insert mapping
        if similarities:
            most_similar_category = max(similarities, key=lambda x: x[1])
            category_id = most_similar_category[0]
        else:
            # Optionally: map by STATUS_CODE if no topic similarity found
            category_id = None  # Could implement a STATUS_CODE mapping table
        
        if category_id is not None:
            insert_sql = f"""
                INSERT INTO PROJECT_BY_CATEGORY ("PROJECT_ID", "CATEGORY_ID")
                VALUES ('{nsman_id}', {category_id})
            """
            cursor.execute(insert_sql)
    
    cursor.close()
    return jsonify({"message": "Categories and project categories updated successfully"}), 200


@app.route('/get_all_project_categories', methods=['GET'])
def get_all_project_categories():
    # Query PROJECT_BY_CATEGORY mapped to NSMAN_ID
    sql_query = """
        SELECT pbc."PROJECT_ID" AS nsman_id, c."category_label"
        FROM "PROJECT_BY_CATEGORY" pbc
        JOIN "CATEGORIES" c ON pbc."CATEGORY_ID" = c."index"
        ORDER BY pbc."PROJECT_ID"
    """
    hana_df = dataframe.DataFrame(connection, sql_query)
    project_categories = hana_df.collect()
    results = project_categories.to_dict(orient='records')
    return jsonify({"nsman_categories": results}), 200


@app.route('/get_categories', methods=['GET'])
def get_categories():
    sql_query = 'SELECT "index", "category_label", "category_descr" FROM "CATEGORIES"'
    hana_df = dataframe.DataFrame(connection, sql_query)
    categories = hana_df.collect()
    results = categories.to_dict(orient='records')
    return jsonify(results), 200

@app.route('/get_advisories_by_expert_and_category', methods=['GET'])
def get_advisories_by_expert_and_category():
    expert_id = request.args.get('nsman_id')
    
    if not expert_id:
        return jsonify({"error": "nsman_id is required"}), 400

    sql_query = f"""
        SELECT c."category_label" AS category, COUNT(a."NSMAN_ID") AS projects
        FROM "PROJECT_BY_CATEGORY" pbc
        JOIN "CATEGORIES" c ON pbc."CATEGORY_ID" = c."index"
        JOIN "MHA_ADVISORIES4" a ON pbc."PROJECT_ID" = a."NSMAN_ID"
        WHERE a."NSMAN_ID" = '{expert_id.replace("'", "''")}'
        GROUP BY c."category_label"
    """
    hana_df = dataframe.DataFrame(connection, sql_query)
    advisories_by_category = hana_df.collect()
    results = advisories_by_category.to_dict(orient='records')
    return jsonify({"advisories_by_category": results}), 200


@app.route('/compare_text_to_existing', methods=['POST'])
def compare_text_to_existing():
    data = request.get_json()
    schema_name = data.get('schema_name', 'DBUSER')
    query_text = data.get('query_text', '')

    if not query_text:
        return jsonify({"error": "query_text is required"}), 400

    similarities = []

    # --- Extract NSMAN_ID ---
    nsman_match = re.search(r'ID\s*=\s*(\d+)', query_text, re.IGNORECASE)
    nsman_id = nsman_match.group(1) if nsman_match else None
    if not nsman_id:
        return jsonify({"error": "NSMAN_ID not found in query_text"}), 400

    # --- Extract LOCATION_NAME (improved regex) ---
    loc_match = re.search(
        r'I want to book a slot\.\s*([A-Za-z0-9\s&\-]+)',
        query_text,
        re.IGNORECASE
    )
    location_name = loc_match.group(1).strip() if loc_match else None

    # --- Extract SLOT_DATE ---
    date_match = re.search(r'(\d{4}-\d{2}-\d{2})', query_text)
    slot_date = date_match.group(1) if date_match else None

    # --- Case 1: If location_name is detected, query BOOKINGS_AVAILABILITY ---
    if location_name:
        slot_query = f"""
            SELECT "LOCATION_NAME", "SLOT_DATE", "SLOT_TIME"
            FROM {schema_name}.BOOKINGS_AVAILABILITY
            WHERE UPPER("LOCATION_NAME") = UPPER('{location_name}')
        """

        if slot_date:
            slot_query += f""" AND "SLOT_DATE" = '{slot_date}' """

        slot_query += """
            ORDER BY "SLOT_DATE" DESC, "SLOT_TIME" DESC
            LIMIT 3
        """

        slot_df = dataframe.DataFrame(connection, slot_query)
        slots = slot_df.collect().to_dict(orient='records')

        solution_vals = [
            f"{slot['LOCATION_NAME']} | {slot['SLOT_DATE']} | {slot['SLOT_TIME']}" 
            for slot in slots
        ]

        similarities.append({
            "NSMAN_ID": nsman_id,
            "SIMILARITY": "1",
            "SOLUTION": solution_vals[0] if len(solution_vals) > 0 else None,
            "SOLUTION_TWO": solution_vals[1] if len(solution_vals) > 1 else None,
            "SOLUTION_THREE": solution_vals[2] if len(solution_vals) > 2 else None,
        })

    # --- Case 2: No location_name → fallback to advisory table ---
    else:
        sql_query = f"""
            SELECT "SOLUTION",
                   "SOLUTION_TWO",
                   "SOLUTION_THREE"
            FROM {schema_name}.MHA_ADVISORIES4
            WHERE "NSMAN_ID" = '{nsman_id}'
            LIMIT 3
        """
        hana_df = dataframe.DataFrame(connection, sql_query)
        solutions = hana_df.collect().to_dict(orient='records')
        for sol in solutions:
            similarities.append({
                "NSMAN_ID": nsman_id,
                "SIMILARITY": "1",
                "SOLUTION": sol["SOLUTION"],
                "SOLUTION_TWO": sol["SOLUTION_TWO"],
                "SOLUTION_THREE": sol["SOLUTION_THREE"]
            })

    return jsonify({"similarities": similarities}), 200


@app.route('/get_project_details', methods=['GET'])
def get_project_details():
    schema_name = request.args.get('schema_name', 'DBUSER')
    project_number = request.args.get('project_number')
    
    if not project_number:
        return jsonify({"error": "Project number is required"}), 400
    
    # SQL query to join ADVISORIES and COMMENTS tables on project_number
    sql_query = f"""
        SELECT a."architect", a."index" AS advisories_index, a."pcb_number", a."project_date", 
               a."project_number", a."solution", a."topic",
               c."comment", c."comment_date", c."index" AS comments_index
        FROM {schema_name}.advisories4 a
        LEFT JOIN {schema_name}.COMMENTS4 c
        ON a."project_number" = c."project_number"
        WHERE a."project_number" = {project_number}
    """
    hana_df = dataframe.DataFrame(connection, sql_query)
    project_details = hana_df.collect()  # Return results as a pandas DataFrame

    # Convert results to a list of dictionaries for JSON response
    results = project_details.to_dict(orient='records')
    return jsonify({"project_details": results}), 200


@app.route('/get_all_projects', methods=['GET'])
def get_all_projects():
    schema_name = request.args.get('schema_name', 'DBUSER')
    
    sql_query = f"""
        SELECT * FROM (
            SELECT a."architect", a."index" AS advisories_index, a."pcb_number", a."project_date", 
                   a."project_number", a."solution", a."topic",
                   c."comment", c."comment_date", c."index" AS comments_index,
                   ROW_NUMBER() OVER (PARTITION BY a."project_number" ORDER BY a."index") AS row_num
            FROM {schema_name}.advisories4 a
            LEFT JOIN {schema_name}.COMMENTS4 c
            ON a."project_number" = c."project_number"
        ) subquery
        WHERE row_num = 1
    """
    hana_df = dataframe.DataFrame(connection, sql_query)
    
    all_projects_df = hana_df.collect()
    all_projects_df = nan_to_null(all_projects_df)  # <-- ensures no NaN

    results = all_projects_df.to_dict(orient='records')
    return jsonify({"all_projects": results}), 200

# -------------------------------
# Root Health Check
# -------------------------------
@app.route('/', methods=['GET'])
def root():
    return 'Embeddings Base API: Health Check Successful.', 200

def create_app():
    return app

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 30000))
    app.run(host="0.0.0.0", port=port, debug=False)
